<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div data-bind="scope: 'knockout'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "knockout": {
                        "component": "Bss_AdminConfig/js/viewModel",
                        "template" : "Bss_AdminConfig/template"
                    }
                }
            }
        }
    }
</script>